### ISSUE TITLE
Add UPC validation to restock tool.

### ISSUE THREAD

**Issue by djrenren** [chezbob/chezbob#31]
Turns out the barcode scanners we use sometimes omit the first and/or last digit from the UPC code. We should reject these invalid scans by ensuring all scans are valid UPCs.

**Comment by alex-bellon** [comment]
Should the check be added on the "Enter" keypress or right when it's scanned:
https://github.com/chezbob/chezbob/blob/a5f4158a092b81aaac3a6d4cfc4914068eae356f/web/static/internal/apps/restock/restock.js#L22-L34

I would assume in the "Enter" keypress if statement since the entire barcode should be taken in by then.

**Comment by djrenren** [comment]
It’s probably clearer to check it in `scan` just so it’s not mixed up with the garbage pile that is detecting input.

**Comment by alex-bellon** [comment]
Closed with #43
